config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :games, only: [:index, :create]
  match 'games/end', to: 'games#destroy', as: 'end_game', via: [:get, :delete]
  patch 'grids/:row/:column', to: 'grids#update', as: 'grids'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grid.rb
class Grid
	attr_accessor :matrix

	def initialize
		self.matrix = Array.new(6, Array.new(7, nil))
  end

  def self.check_winner(player, matrix, row, column)
    horizontal_matches = 0
    vertical_matches = 0
    upward_diagonal_matches = 0
  	downward_diagonal_matches = 0

    # Check horizontally
    start = (column - 1) == -1 ? 0 : (column - 1)

  	for i in start.downto(0)
      break if matrix[row][i] != player['number']
  		horizontal_matches += 1
  	end

    for i in column..6
  		break if matrix[row][i] != player['number']
  		horizontal_matches += 1
  	end

    # Check vertically
    start = (row - 1) == -1 ? 0 : (row - 1)
    
    for i in start.downto(0)
      break if matrix[i][column] != player['number']
      vertical_matches += 1
    end

    for i in row..5
      break if matrix[i][column] != player['number']
      vertical_matches += 1
    end

    # Check upward diagonal
    start_row = row - 1
    start_column = column + 1

    until start_row < 0 or start_column > 6 do
      break if matrix[start_row][start_column] != player['number']
      start_row -= 1
      start_column += 1
      upward_diagonal_matches += 1
    end
    
    start_row = row + 1
    start_column = column - 1

    until start_row > 5 or start_column < 0 do
      break if matrix[start_row][start_column] != player['number']
      start_row += 1
      start_column -= 1
      upward_diagonal_matches += 1
    end

    upward_diagonal_matches += 1

    # Check downward diagonal
    start_row = row - 1
    start_column = column - 1

    until start_row < 0 or start_column < 0 do
      break if matrix[start_row][start_column] != player['number']
      start_row -= 1
      start_column -= 1
      downward_diagonal_matches += 1
    end
    
    start_row = row + 1
    start_column = column + 1

    until start_row > 5 or start_column > 6 do
      break if matrix[start_row][start_column] != player['number']
      start_row += 1
      start_column += 1
      downward_diagonal_matches += 1
    end

    downward_diagonal_matches += 1

  	(horizontal_matches >= 4 or vertical_matches >= 4 or upward_diagonal_matches >= 4 or downward_diagonal_matches >= 4) ? player : nil
  end
end

app/models/player.rb
class Player
	attr_accessor :number, :first_name, :color

	def initialize(number, first_name, color)
		self.number = number
		self.first_name = first_name
		self.color = color
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	def index
	end

	def create
		session[:grid] = Grid.new
		session[:in_game] = true
		session[:player_one] = Player.new(1, params[:player_one], "blue")
		session[:player_two] = Player.new(2, params[:player_two], "red")

		session[:current_player] = session[:player_one]

		redirect_to games_path
	end

	def destroy
		session.destroy
		redirect_to root_path
	end
end

app/controllers/grids_controller.rb
class GridsController < ApplicationController
	def update
		if session[:game_winner].nil?
			row = params[:row].to_i
			column = params[:column].to_i
			session[:grid]['matrix'][row][column] = session[:current_player]['number']

			session[:game_winner] = Grid.check_winner(session[:current_player], session[:grid]['matrix'], row, column)
			
			if session[:current_player]['number'] == 1
				session[:current_player] = session[:player_two]
			elsif session[:current_player]['number'] == 2
				session[:current_player] = session[:player_one]
			end
		end
		
		respond_to do |format|
			format.json { render json: {
					current_player_name: session[:current_player]['first_name'],
					current_player_color: session[:current_player]['color'],
					game_winner: session[:game_winner]
				},
				status: :ok
			}
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_form.html.haml
= form_tag games_path, class: "ui sixteen form" do
	.field
		= label_tag :player_one do
			%i.blue.user.icon
			Player 1
		= text_field_tag :player_one, nil, required: true
	.field
		= label_tag :player_two do
			%i.red.user.icon
			Player 2
		= text_field_tag :player_two, nil, required: true
	= button_tag type: :submit, class: "ui green button" do
		%i.play.icon
		Start Game

app/views/games/index.html.haml
= render "layouts/header"

- if session[:game_winner].nil?
  .centered.row#disc-container
    .column
      .disc.draggable{data: {color: session[:current_player]['color']}}
    .middle.aligned.column
      %h3#current-player-name= session[:current_player]['first_name']

- if session[:game_winner].nil?
  .centered.row#winner-display
    %h2
      Winner: 
      %span#winner-name
- else
  .centered.row
    %h2
      Winner: 
      %span= session[:game_winner]['first_name']

.centered.row#board-container
  %table#game-board
    - if session[:game_winner].nil?
      %tr.droppable-area
        - for column in 0..6
          %td.droppable{data: {column: column}} drop
    - for row in 0..5
      %tr
        - for column in 0..6
          %td{id: "area-#{row}-#{column}", class: session[:grid]['matrix'][row][column].nil? ? "" : "player-#{session[:grid]['matrix'][row][column]}-color occupied", data: {row: row, column: column}}

.centered.row
  = button_to "End Game", end_game_path, method: :delete, class: "ui red button"

app/views/home/index.html.haml
.centered.sixteen.wide.row#game-form-container
	.ten.wide.mobile.seven.wide.tablet.four.wide.computer.center.aligned.column
		.ui.card
			%h2 Connect Four
			= render "games/form"

app/views/layouts/_header.html.haml
.centered.row#header
	%h2 Connect Four

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ConnectFour
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.ui.grid
    = yield